import {
  ReactIcon,
  NextJSIcon,
  ExpoIcon,
  FlutterIcon,
  ReactNativeIcon,
  StripeIcon,
  TailwindIcon,
  TypeScriptIcon,
  JavaScriptIcon,
  DartIcon,
  ReduxIcon,
  MobxIcon,
  BlocIcon,
  BranchIcon,
  ZustandIcon,
  NodeJsIcon,
  ExpressJsIcon,
  HtmlIcon,
  CssIcon,
  FirebaseIcon,
  MongoDBIcon,
  MySQLIcon,
  AdobeXdIcon,
  FigmaCIcon,
  PhpIcon,
  LaravelIcon,
  BootstrapIcon,
  SupabaseIcon,
  SocketIoIcon,
  GoogleMapsIcon,
  MoEngageIcon,
  RealmIcon,
  SQLiteIcon,
  CodePushIcon,
} from "./react-icon";

export const techStackMap: Record<string, JSX.Element> = {
  react: <ReactIcon />,
  nextjs: <NextJSIcon />,
  typescript: <TypeScriptIcon />,
  tailwind: <TailwindIcon />,
  stripe: <StripeIcon />,
  "react native": <ReactNativeIcon />,
  expo: <ExpoIcon />,
  flutter: <FlutterIcon />,
  javascript: <JavaScriptIcon />,
  dart: <DartIcon />,
  redux: <ReduxIcon />,
  mobx: <MobxIcon />,
  zustand: <ZustandIcon />,
  nodejs: <NodeJsIcon />,
  expressjs: <ExpressJsIcon />,
  html: <HtmlIcon />,
  css: <CssIcon />,
  firebase: <FirebaseIcon />,
  mongodb: <MongoDBIcon />,
  mysql: <MySQLIcon />,
  figma: <FigmaCIcon />,
  "adobe xd": <AdobeXdIcon />,
  supabase: <SupabaseIcon />,
  php: <PhpIcon />,
  laravel: <LaravelIcon />,
  bootstrap: <BootstrapIcon />,
  "socket.io": <SocketIoIcon />,
  "google-maps": <GoogleMapsIcon />,
  moengage: <MoEngageIcon />,
  realm: <RealmIcon />,
  branch: <BranchIcon />,
  bloc: <BlocIcon />,
  "code push": <CodePushIcon />,
  sqlite: <SQLiteIcon />,
};
